name: CI
on:
   # События, которые запускают jobs
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

# jobs запускаются параллельно, если не указана последовательность
jobs:
    # Название job вы можете назвать как угодно
    my_build_job:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
      steps:
          # Actions от github: проверяет репозиторий, гит и т.д.
          - uses: actions/checkout@v3
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'

          - name: Grant execute permissions to Gradle wrapper
            run: chmod +x gradlew
      
          - name: Validate Gradle wrapper
            uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      
          - name: Run test
            run: ./gradlew test
      
          - name: Generate JaCoCo Badge
            uses: cicirello/jacoco-badge-generator@v2
            with:
                jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv